### ISSUE TITLE
Duplicate username and email inserted

### ISSUE THREAD

**Issue by keithazzopardi** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#11]
Steps to reproduce:
 - Set user to the same username and/or email
 - Configure Services with unique email:

`            services.AddIdentity<ApplicationUser, ApplicationRole>(options =>
            {
                options.User = new UserOptions
                {                    
                    RequireUniqueEmail = true
                };
})`

var resultTask1 = userManager.CreateAsync(user1, password);
var resultTask2 = userManager.CreateAsync(user2, password);
await Task.WhenAll(resultTask1, resultTask2);

Result:
2 records are inserted into Mongo

Expected result
1 record should be inserted in Mongo

**Comment by alexandre-spieser** [comment]
This is expected behaviour if you do not set constraints in MongoDB and insert 2 docs concurrently.
Microsoft's Identity manager does not check for this either and relies on SQL Server to throw a duplicate key exception when a concurrent insert occurs, because constraints are set in EF's OnModelCreating method.

A solution to your problem is to add unique compound index to the user collection, but this is not the userManager's responsibility.

More info here:

https://stackoverflow.com/questions/24122981/how-to-stop-insertion-of-duplicate-documents-in-a-mongodb-collection
