### ISSUE TITLE
System.TypeLoadException when using with GenericRepository

### ISSUE THREAD

**Issue by gterdem** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#13]
Hello,

When used with [generic repository](https://github.com/alexandre-spieser/mongodb-generic-repository) 
`System.TypeLoadException: 'Could not load type 'MongoDbGenericRepository.IMongoDbCollectionIndexRepository' from assembly 'MongoDbGenericRepository, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.'`

error occurs on:
`services.AddIdentity<ApplicationUser, ApplicationRole>()
                .AddMongoDbStores<ApplicationUser, ApplicationRole, Guid>(taskDbContext)
                .AddDefaultTokenProviders();`

It is probably because of this package's internally dependency on IMongoDbCollectionIndexRepository while [GenericRepository](https://github.com/alexandre-spieser/mongodb-generic-repository) has the same interface with different assembly version

**Comment by alexandre-spieser** [comment]
Are you using MongoDbGenericRepository 1.3.8?

Le 21 avr. 2019 15:54, Galip Erdem <notifications@github.com> a écrit :

Hello,

When used with generic repository<https://github.com/alexandre-spieser/mongodb-generic-repository>
System.TypeLoadException: 'Could not load type 'MongoDbGenericRepository.IMongoDbCollectionIndexRepository' from assembly 'MongoDbGenericRepository, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.'

error occurs on:
services.AddIdentity<ApplicationUser, ApplicationRole>() .AddMongoDbStores<ApplicationUser, ApplicationRole, Guid>(taskDbContext) .AddDefaultTokenProviders();

It is probably because of this package's internally dependency on IMongoDbCollectionIndexRepository while GenericRepository<https://github.com/alexandre-spieser/mongodb-generic-repository> has the same interface with different assembly version

**Comment by gterdem** [comment]
Hello,

It is 1.4.0. I think i tried to downgrade to 1.3.8 also it didn't work.

**Comment by alexandre-spieser** [comment]
Try downgrading and clear your cache/ build folder. 1.4.0 is not compatible yet because I renamed this interface. For the downgrade please use the version referenced in the AspNetCore.Identity.MongoDbCore nuget package.

Le 21 avr. 2019 21:54, Galip Erdem <notifications@github.com> a écrit :

Hello,

It is 1.4.0. I think i tried to downgrade to 1.3.8 also it didn't work.

**Comment by alexandre-spieser** [comment]
I have upgraded the package dependencies.
https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/releases/tag/1.1.1
