### ISSUE TITLE
Missing DbContext

### ISSUE THREAD

**Issue by clintnetwork** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#21]
Hi,

How to configure a DbContext using this library?

Thank you!

**Comment by alexandre-spieser** [comment]
Hello,

The concept of DbContext does not exist with MongoDb, since the DbContext is EF/SQL specfic.
In the docs available here, you can created a `MongoDbContext`:
https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/blob/master/README.md


# Configuration
To add the stores, you can use the `IdentityBuilder` extension like so:

```csharp
services.AddIdentity<ApplicationUser, ApplicationRole>()
	.AddMongoDbStores<ApplicationUser, ApplicationRole, Guid>
	(
		"mongodb://localhost:27017",
		"MongoDbTests"
	)
	.AddDefaultTokenProviders();
```


It is also possible to share a common `IMongoDbContext` across your services (requires https://www.nuget.org/packages/MongoDbGenericRepository/):

```csharp
var mongoDbContext = new MongoDbContext("mongodb://localhost:27017", "MongoDbTests");
services.AddIdentity<ApplicationUser, ApplicationRole>()
	.AddMongoDbStores<IMongoDbContext>(mongoDbContext)
	.AddDefaultTokenProviders();
// Use the mongoDbContext for other things.
```

You can also use the more explicit type declaration:

```csharp
var mongoDbContext = new MongoDbContext("mongodb://localhost:27017", "MongoDbTests");
services.AddIdentity<ApplicationUser, ApplicationRole>()
	.AddMongoDbStores<ApplicationUser, ApplicationRole, Guid>(mongoDbContext)
	.AddDefaultTokenProviders();
// Use the mongoDbContext for other things.
```

Alternatively a full configuration can be done by populating a `MongoDbIdentityConfiguration` object, which can have an `IdentityOptionsAction` property set to an action you want to perform against the `IdentityOptions` (`Action<IdentityOptions>`).

The `MongoDbSettings` object is used to set MongoDb Settings using the `ConnectionString` and the `DatabaseName` properties.

The MongoDb connection is managed using the [mongodb-generic-repository](https://github.com/alexandre-spieser/mongodb-generic-repository), where a repository inheriting `IBaseMongoRepository` is registered as a singleton. Look at the [ServiceCollectionExtension.cs](https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/blob/master/src/Extensions/ServiceCollectionExtension.cs) file for more details.

**Comment by clintnetwork** [comment]
Hi,

Thanks for your full answer, I already do that but when I build I have a missing DbContext error, it's the reason why I throw this issue!

Thank you

**Comment by alexandre-spieser** [comment]
Are you using Identity 2.0 ? This package does not support Identity 3.0.
Also, make sure that you do not have an EntityFramework packages doing Identity related work.
The stores used must only be the MongoDb ones, make sure you do not have any UserStore needing a DbContext.

**Comment by clintnetwork** [comment]
I use net core 3 ^^

**Comment by alexandre-spieser** [comment]
yeah that might be the reason why it's not working, Identity 3.0 is almost a full rewrite, because they integrated the Identity Server package, the data access layer is totally different. This package does not support it yet.

**Comment by clintnetwork** [comment]
Oh I see, do you plan to migrate to net core 3?

**Comment by alexandre-spieser** [comment]
yeah but it's not a 5 minute job 😄

**Comment by knight1219** [comment]
So interestingly, I've got it to compile and run using .net Core 3.1, but 26 tests seem to be failing (most seem to be related to the SecurityStamp). I'm not sure of the impact of those 26 tests failing but, its something.
