### ISSUE TITLE
Update for Blazor?

### ISSUE THREAD

**Issue by clawton** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#26]
This looks like a great project and that you recently provided support for .NET Core 3.1.  I'm new to ASP.NET and would like to use this with a Blazor (server) app.  But since I'm so new to ASP.NET and Blazor, I can't really figure how to start using this Identity service with Blazor.  I'm sure it would be really simple for you.  Would you be willing to update your test site with a Blazor version?

Keep up the good work,
Chris

**Comment by leandromendes-ifthen** [comment]
Im also in the same boat here! And i would love to know how to apply this in blazor

**Comment by xclud** [comment]
This would be the same as normal AP.NET Core projects. I believe you can get started using the example project.

Anyway, you may not want to do database related things on client size. As you know parts of Blazor may run on client machine. Just make sure everything related to database and authentication remains on the server. That's why the example project will be enough to get started.

**Comment by clawton** [comment]
Thanks.  Was able to get it working a couple days ago on server side so I'm actually good.

**Comment by leandromendes-ifthen** [comment]
@clawton anyway can you provide a sample?
