### ISSUE TITLE
No service for type 'UserManager<IdentityUser>' has been registered.

### ISSUE THREAD

**Issue by MisinformedDNA** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#28]
I have the sample running successfully in VS 2019 (with the following lines removed):

```
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
    <AspNetCoreModuleName>AspNetCoreModule</AspNetCoreModuleName>
```

But if I create a new ASP.NET Core MVC App and add the nuget package, I get the error:

> InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser]' has been registered.

In an effort to figure it out, I
- Copied the PackageReferences in the CSPROJ file to mine
- Copied the `Configure` and `ConfigureServices` methods to mine
- Copied over the appsettings and run the new app

But I keep getting the error:

> InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.UserManager`1[Microsoft.AspNetCore.Identity.IdentityUser]' has been registered.

Any ideas why this is failing for my new app?

**Comment by MisinformedDNA** [comment]
I figured it out, though I don't like the solution...

First `IdentityUser` is used in all the default Identity templates, so, by default, `_LoginPartial.cshtml` is looking for a binding to `UserManager<IdentityUser>` and no matching service could be found. 

Looking at the inheritance chain, I found that 
- `MongoIdentityUser` inherits from `IdentityUser<Guid>`
- `IdentityUser` inherits from `IdentityUser<string>`

So that explains why this error keeps showing up: `MongoIdentityUser` doesn't actually inherit from `IdentityUser`.

I don't know how you can clearly communicate this through code, so at the very least, the documentation should show how to convert a default Identity template to use this provider instead.

**Comment by alexandre-spieser** [comment]
Hello thanks for your message. Not sure what the issue is here.
`the documentation should show how to convert a default Identity template to use this provider instead.`  <= That's why I converted the [MVC sample that was in the repo](https://github.com/aspnet/Identity/tree/b865d5878623077eeb715e600d75fa9c24dbb5a1/samples/IdentitySample.Mvc) :
https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/tree/b3db4eb39fcd2d1f0df59ffbb6933dc53f794476/sample/MongoIdentitySample.Mvc.

Where the partial is indeed different:
https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/blob/master/sample/MongoIdentitySample.Mvc/Views/Shared/_LoginPartial.cshtml

```
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
```
`UserManager<IdentityUser>` cannot work in this package.
As mentioned in the docs:

> Your user and role entities must inherit from `MongoIdentityUser<TKey>` and `MongoIdentityRole<TKey>` in a way similar to the `IdentityUser<TKey>` and the `IdentityRole<TKey>` in Microsoft.AspNetCore.Identity, where TKey is the type of the primary key of your document.

If you really want string primary keys:
```
public class MyUser : MongoIdentityUser<string>
{
	public MyUser () : base()
	{
	}

	public MyUser (string userName, string email) : base(userName, email)
	{
	}
}
```
with matching role:
```
public class ApplicationRole : MongoIdentityRole<string>
{
	public ApplicationRole() : base()
	{
	}

	public ApplicationRole(string roleName) : base(roleName)
	{
	}
}
```
then:
```
services.AddIdentity<ApplicationUser, ApplicationRole>()
	.AddMongoDbStores<ApplicationUser, ApplicationRole, string>
	(
		"mongodb://localhost:27017",
		"MongoDbTests"
	)
	.AddDefaultTokenProviders();
```
As highlighted in:
https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore#user-and-role-entities

If you feel like the docs are not clear enough please feel free to raise a PR. I understand your frustration but unfortunately I cannot satisfy everyone. I advise you to copy the sample and use it as a boiler plate for your project to avoid issues.

I hope this makes sense.

**Comment by MisinformedDNA** [comment]
Right, it says

> Your user and role entities must inherit from MongoIdentityUser<TKey> and MongoIdentityRole<TKey>

but it doesn't call out that MongoIdentityUser doesn't inherit from IdentityUser, nor does it call out that the partial needs to be updated. These should be called out in the README.

> That's why I converted the [MVC sample that was in the MSFT repo](https://github.com/aspnet/Identity/tree/b865d5878623077eeb715e600d75fa9c24dbb5a1/samples/IdentitySample.Mvc)

Samples are nice, but is it your intention that we copy your sample as a starting point? Maybe that works fine for MVC, but that leaves out people who are developing Razor Pages or Blazor apps. Because of that, the README should call out the bare minimum to get started, regardless of project type.
