### ISSUE TITLE
Deleting a role doesn't remove it from users

### ISSUE THREAD

**Issue by AssafTzurEl** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#33]
If a user is linked to a role (it's in his Roles array) and I delete that role from the roles collection using RoleManager.DeleteAsync(), the link remains with the user, which causes integrity problems later on.

Is this a Microsoft Identity problem or yours?

**Comment by alexandre-spieser** [comment]
Hi, Microsoft does the same, however with Microsofts package for SQL your will have a Foreign Key exception. MongoDB is no sql, so it allows the deletion.With MongoDB it's up to the application logic to handle integrity issues.Le 29 juil. 2020 10:23, Assaf Tzur-El <notifications@github.com> a écrit :
If a user is linked to a role (it's in his Roles array) and I delete that role from the roles collection using RoleManager.DeleteAsync(), the link remains with the user, which causes integrity problems later on.
Is this a Microsoft Identity problem or yours?

**Comment by AssafTzurEl** [comment]
This is silly - I have to write code that removes deleted roles from all users, just like I had to write tons of code for deleting claims from all roles and users. Should have been handled by the framework (MS's). I'll ask my manager for approval to publish my code as a wrapper for yours. Or would you like it to be added to your framework?

**Comment by alexandre-spieser** [comment]
If you can make the framework throw if it tries to delete Roles that are referenced in the users collection that would be helpful. This is the closest to what the Microsoft framework does. Please do not delete other things in that method, just make it throw an error like a Foreign Key db exception.You would have to get the users collection name in order to query things in a generic fashion for the framework to work. Not sure if the RoleStore has access to the IdentityUser type to get the collection name. I am in the middle of a house move so cannot review much code at the moment. I hope this helps.Le 29 juil. 2020 14:39, Assaf Tzur-El <notifications@github.com> a écrit :
This is silly - I have to write code that removes deleted roles from all users, just like I had to write tons of code for deleting claims from all roles and users. Should have been handled by the framework (MS's). I'll ask my manager for approval to publish my code as a wrapper for yours. Or would you like it to be added to your framework?
