### ISSUE TITLE
Does this work with .net5? 

### ISSUE THREAD

**Issue by johnkwaters** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#45]
Also, I m wanting to use this with Duende IdentityServer - anyone tried that?

**Comment by alexandre-spieser** [comment]
Hello, sorry I have not tried with .NET 5 nor Duende, I currently use it with Identity Server V4 and .NET Core 3.0.

**Comment by Damian-Coutts** [comment]
I have an updated local branch built against net5.0. Only changes seem to be accomodating the removal of user ids from error messages in tests. Would it help if I pushed that branch. I'd like a 5.0 package as well.

**Comment by alexandre-spieser** [comment]
Hi Damian, thanks for reaching out, yeah sure feel free to raise a PR and I'll have a look! :) 
I'm curious about the issue with userIds you're decsribing.

**Comment by Damian-Coutts** [comment]
Alexandre
Thanks for your great package. I found it is particularly a good fit for Autodesk Forge applications.
I don’t often contribute to open source so I may be doing something wrong, but I don’t believe I have access to push the branch:
remote: Permission to alexandre-spieser/AspNetCore.Identity.MongoDbCore.git denied to Damian-Coutts.

The issue with the user ids is that the 5.0 identity framework no longer returns the user if in error messages. The tests were all expecting errors like:User OISDFG8D790 is currently locked out
Rather than
User is currently locked out.
Let me know how I should best share this code with you.
Regards
Damian Coutts

**Comment by weirdyang** [comment]
Hi, I've managed to get it to work with a .net5.0 blazor client; https://github.com/weirdyang/openiddict-core-mongo-identity

**Comment by alexandre-spieser** [comment]
@Damian-Coutts sorry for the delayed reply, I was away on holiday. Can you please fork this repo's master branch and raise a pull request with your changes ? :)

**Comment by toiyabe** [comment]
Hello!
Related question: anyone try this with .Net Core 6.x and latest Entity Framework?
Thanks in advance!

**Comment by alannsiqueira** [comment]
any update?

**Comment by Damian-Coutts** [comment]
My inital problems with the package are resolved. I am in production with .NET Core 6 for  while now with no problems.
Great work Alexandre

**Comment by alexandre-spieser** [comment]
Thanks. Yes I can confirm that it should work with .net 5 and .net 6, not experiencing any issue either.
